G.strings = {
	gameTitle : "ELEMENTIS",
	firstPlayerName : "purple",
	secondPlayerName : "orange",
	thirdPlayerName : "blue",
	fourthPlayerName : "magenta",
	computerPlayerName : "computer",
	thinkingMessage : "thinking...",
	firstVictory : "purple won!",
	secondVictory : "orange won!",
	thirdVictory : "blue won!",
	fourthVictory : "magenta won!",
	tieGame : "tie game",
	fireName : "fire",
	earthName : "earth",
	waterName : "water",
	airName : "wind",
	fireAttack : "burns",
	earthAttack : "dries",
	waterAttack : "extinguishes",
	airAttack : "blows",
	playAction : "played",
	prePosition : "at",
	turn : "turn",
	possesive : "'s",
	plural : "s",
	pvpEasy : "player vs player (easy)",
	pvpDef : "player vs player (defense)",
	pvcEasy : "player vs computer (easy)",
	pvcDef : "player vs computer (hard)",
	optionsButton : "options",
	optionsMenu : "options",
	undoButton : "undo",
	redoButton : "redo",
	gamelogToggleButton : "toggle log",
	newGameButton : "start new game",
	exitGameButton : "exit game",
	closeMenuButton : "continue",


};